baseurl: /yoga-blog
title: Yoga
subtitle: Learning Yoga
author: Marcus Svehlak
simple_search: http://google.com/search
description: A Yoga Jekyll
name: Yoga Marcus
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
timezone: America/Los_Angeles
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
donations:
  paypal:
    text: Donate
    id: JHP8TVQKRMRVS  # PayPal button ID
include:
  - _downloads
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/clayh53.github.com/
